metadata:
  name: init-tenant-db
  labels:
    service: init-tenant-db
  annotations:
    configmap.fabric8.io/update-on-change: "init-tenant"
spec:
  replicas: 1
  selector:
    service: init-tenant-db
  template:
    metadata:
      labels:
        service: init-tenant-db
    spec:
      containers:
      - name: init-tenant-db
        image: registry.centos.org/postgresql/postgresql:9.6
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: f8tenant
              key: postgres.password
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql
          name: init-tenant-postgresql-data
          readOnly: false
      volumes:
      - name: init-tenant-postgresql-data
        persistentVolumeClaim:
          claimName: init-tenant-postgresql-data