apiVersion: v1
kind: ConfigMap
metadata:
  name: wit
  annotations:
    expose.service-key.config.fabric8.io/keycloak: keycloak.url
    expose-no-path.service-key.config.fabric8.io/auth: auth.url
type: Opaque
data:
  db.host: wit-db
  db.port: 5432
  auth_notapproved_redirect: ""
  chestarter.url: http://che-starter:10000
  auth.url: http://auth
  authz.enabled: "true"
  keycloak.url: http://keycloak
  openshift.tenant.masterurl: http://kubernetes.default/
  postgres.connection.maxidle: "90"
  postgres.connection.maxopen: "90"
  # TODO
  #postgres.sslmode: require
  postgres.sslmode: disable
  redirect.valid: ".*"
  tenant.serviceurl: http://kubernetes.default/