apiVersion: v1
kind: ConfigMap
metadata:
  name: che-starter
  annotations:
    expose.config.fabric8.io/apiserver-key: oso.address
type: Opaque
data:
  oso.domain.name: localhost
  oso.address: localhost:8443
  oso.tokenurl: http://keycloak/auth/realms/fabric8/broker/openshift-v3/token
  github.tokenurl: http://keycloak/auth/realms/fabric8/broker/github/token
  fabric8.dev.mode: true
  che.keycloak.auth.server.url: http://keycloak/auth
  che.keycloak.realm: fabric8
  che.keycloak.client.id: fabric8-online-platform
