apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric8
  annotations:
    # when using the proxy 
    #expose.config.fabric8.io/url-key: proxy.pass.url
    #expose.config.fabric8.io/url-key: proxy.pass.url
    #expose.config.fabric8.io/host-key: proxy.pass.server
    expose.config.fabric8.io/url-key: apiserver.url
    expose.config.fabric8.io/host-key: apiserver.host
    expose.config.fabric8.io/console-url-key: openshift.console.url
    #expose.config.fabric8.io/apiserver-key: proxy.pass.server
    expose.config.fabric8.io/apiserver-url-key: proxy.pass.url
    expose.config.fabric8.io/apiserver-key: ws.apiserver.host
    #expose.config.fabric8.io/apiserver-key: apiserver.host
    #expose.config.fabric8.io/apiserver-url-key: apiserver.url
    expose-full.service-key.config.fabric8.io/sso: keycloak.url
    expose-full.service-key.config.fabric8.io/wit: wit.api.url
    expose-full.service-key.config.fabric8.io/f8tenant: f8tenant.api.url
    expose.service-key.config.fabric8.io/forge: forge.api.url
    #expose.config.fabric8.io/apiserver-protocol-key: apiserver.protocol
    expose.config.fabric8.io/protocol-key: apiserver.protocol
data:
  apiserver.host: kubernetes
  apiserver.url: http://kubernetes
  apiserver.base.path: "/_p/oso"
  ws.apiserver.host: kubernetes
  ws.apiserver.base.path: ""
  ws.apiserver.protocol: wss
  proxy.pass.server: ""
  proxy.pass.url: ""
  apiserver.protocol: http
  keycloak.url: http://keycloak
  forge.api.url: http://generator-backend
  wit.api.url: http://wit
  f8tenant.api.url: http://f8tenant
  openshift.console.url: ""
  recommender.api.url: ""